---
- hosts: localhost
  connection: local
  force_handlers: True

  roles:
    - role: pegasyseng.hyperledger_besu
      vars:
#       besu_build_from_source: true
        besu_build_from_source: false
#       besu_git_repo: https://github.com/benjamincburns/besu.git
#       besu_git_commit: getbytes-fix
        besu_version: PARAM_BESU_VERSION
        besu_sync_mode: FULL
        besu_network: ibft
        besu_rpc_http_api: ["DEBUG","NET","WEB3","ETH","ADMIN","IBFT","EEA","PRIV"]
        besu_genesis_path: /etc/besu/genesis.json
        besu_bootnodes: ["enode://05e2aab6df08db103fd75c4fb2b8582fe43eebce6a0f077b590a5e7f44ed081e498fa2c57788372d7bc0c41a34394f34c5c11332f4473a1bdf83589316edc2c4@PARAM_BESU_BOOTNODE_IP:30303"]
        besu_host_ip: PARAM_BESU_HOST_IP
        besu_download_url: "PARAM_BESU_DOWNLOAD_URL"
        besu_cmdline_args: ["--tx-pool-max-size=100000"]
        besu_log_level: INFO
#       besu_env_opts: '"-XX:StartFlightRecording=disk=true,delay=15s,dumponexit=true,filename=/tmp/recording.jfr,maxsize=1024m,maxage=1d,settings=profile,path-to-gc-roots=true" "-Xmx8G"'
        besu_env_opts:
#         - "-XX:+HeapDumpOnOutOfMemoryError"
#         - "-XX:HeapDumpPath=/tmp/oom_heap_dump.hprof"
#         - "-Xlog:gc*"
          - "-Xmx8G"
        besu_privacy_enabled: "true"
        besu_privacy_public_key_file: "/etc/besu/orion.pub"
        besu_privacy_url: "http://PARAM_BESU_PRIVACY_IP:8888"
        besu_min_gas: 0


    - { role: undergreen.prometheus-node-exporter, become: yes }